### ISSUE TITLE
/bin/sh: ./start.sh: not found

### ISSUE THREAD

**Issue by mercyground** [JasonHHouse/gaps#255]
**Describe the bug**
Pulled latest housewrecker/gaps:arm-latest docker image. Image fails to load with /bin/sh: ./start.sh: not found

Tried to get a shell but fails as image bootloops.

```
root@ubuntu:/opt/gaps# docker logs gaps
/bin/sh: ./start.sh: not found
/bin/sh: ./start.sh: not found
/bin/sh: ./start.sh: not found
/bin/sh: ./start.sh: not found
/bin/sh: ./start.sh: not found
```

```
root@ubuntu:/opt/gaps# docker exec -it gaps /bin/bash
Error response from daemon: Container b2b4fc90b19d548c35ce571a052735680e0089b43109a7e04f967b99467cdcab is restarting, wait until the container is running
```

**To Reproduce**
Pull latest housewrecker/gaps:arm-latest docker image.
Reload and check logs.

**Expected behavior**
Gaps to start? :)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Ubuntu on Raspberry Pi4 4gb
Gaps version should be latest. Unable to confirm from docker image.

Docker file is as follows : 

```
version: '3.3'
services:
    gaps:
        ports:
            - '8484:8484'
        container_name: gaps
        expose:
            - '32400'
        volumes:
            - '/media/plex/config/gaps:/usr/data'
        image: 'housewrecker/gaps:arm-latest'
        restart: unless-stopped
```
