### ISSUE TITLE
Not able to run (by java -jar and also Docker)

### ISSUE THREAD

**Issue by prinzpi** [JasonHHouse/Gaps#52]
Hi,
unfortunately I'm not able to execute gaps.

I have the same issue as here described:
https://github.com/JasonHHouse/Gaps/issues/47

With Docker:
`Fatal: Need to specify DB_API_KEY as environment variable Refer to README.md
`

With java -jar command:
```
(...) 
Caused by: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
(...)
```

I have tried to fix it with following instruction:

> I fixed the issue by moving the Gaps jar file to the resources directory with application.yaml then fixing spacing issues within the yaml file.

But the issue is still not fixed for me.

My application.yml file (inside where this file is located is also the Gaps-0.0.3.jar file):
```

  gaps:
  #Put your Plex Movie All URLs here
  #Gaps supports a single movie URL or multiple.
  #Single
  #movieUrls:
  - http://192.168.0.101:32400/library/sections/7/all/?X-Plex-Token=<myPlexToken>
  - http://192.168.0.101:32400/library/sections/5/all/?X-Plex-Token=<myPlexToken>

  #Go to https://www.themoviedb.org and make an API Key, place that key here
  #movieDbApiKey: {key}
  movieDbApiKey: <myMovieDBAPIKey>

  # Optional
  # Go to https://www.themoviedb.org and make a custom list for GAPS https://www.themoviedb.org/list/<id number>
  # enter the <id number> below if you want GAPS to populate the list
  movieDbListId:

  #Should Gaps write out to a file as well as console
  writeToFile: true


  #######################################
  #
  #Can read from a folder, Plex, or both
  #At least, one of the two property groups needs to be filled in though
  #
  #######################################

  #List of folders where movies can be pulled from
  folder:
    #Required
    searchFromFolder: true

    #Required if searching from folders
    #List of folders to search in
    folders:
      - /media/NAS/Filme
      - /media/NAS3/Filme

    #Required if searching from folders
    #If the subfolder should be searched in
    recursive: true

    #Required if searching from folders
    #Add any movie formats as needed
    movieFormats:
      - avi
      - mkv
      - mp4
      - mov
      - webm
      - vob
      - flv
      - mts
      - m2ts
      - m4p
      - m4v
      - 3gp
      - 3g2

    #Movie Regex
    #Expected format is Movie Name (Year)
    #Example: The Fast and the Furious (2001)
    yearRegex: \(([1-2][0-9][0-9][0-9])\)

  #Plex connection timeouts when querying for all movies in the Plex section. Time is in seconds. Default is 180 seconds
  plex:
    searchFromPlex: false
    connectTimeout: 180
    writeTimeout: 180
    readTimeout: 180

    #Mulitple
    #movieUrls:
    #  - http://127.0.0.1:32400/library/sections/1/all/?X-Plex-Token={My-Plex-Token}
    #  - http://127.0.0.1:32400/library/sections/2/all/?X-Plex-Token={My-Plex-Token}
    #  - http://127.0.0.1:32400/library/sections/3/all/?X-Plex-Token={My-Plex-Token}
    movieUrls:
       - http://192.168.0.101:32400/library/sections/7/all/?X-Plex-Token=<myPlexToken>
       - http://192.168.0.101:32400/library/sections/5/all/?X-Plex-Token=<myPlexToken>

  #Adjust logging as you see fit
  logging:
  level:
    root: INFO

```
So the spacing issues should also be fixed... There were some error messages regarding the spacing / indents, so I thought I'm on the right way to fix it... But after there wasn't any spacing / indents issues anymore... I have received again the old error message.
